export const orderStatuses = [
  "All Statuses",
  "Processing",
  "Shipped",
  "Delivered",
  "Pending Review",
  "Cancelled",
];

export const paymentGateways = [
  "All Gateways",
  "Mada",
  "Apple Pay",
  "Cash on Delivery",
];

export const mockOrders = [
  {
    id: "NX-89421",
    priority: "urgent",
    customer: "Sultan Al-Otaibi",
    phone: "+966 50 *** 4821",
    location: "Riyadh, Al-Nakheel",
    skuSummary: "2x Royal Taif Rose Oil + 1x Handcrafted Oud Burner",
    status: "Processing",
    gateway: "Mada",
    total: 1240.0,
  },
  {
    id: "NX-89420",
    priority: null,
    customer: "Noura Al-Ghamdi",
    phone: "+966 54 *** 1928",
    location: "Jeddah, Al-Shati",
    skuSummary: "1x Premium Embroidered Silk Abaya",
    status: "Shipped",
    gateway: "Apple Pay",
    total: 890.0,
  },
  {
    id: "NX-89419",
    priority: null,
    customer: "Abdulrahman Al-Dosari",
    phone: "+966 55 *** 9301",
    location: "Dammam, Corniche",
    skuSummary: "3x Aged Kalakassi Agarwood (6 tola)",
    status: "Delivered",
    gateway: "Mada",
    total: 3120.0,
  },
  {
    id: "NX-89418",
    priority: "flagged",
    customer: "Reem Al-Khatib",
    phone: "+966 56 *** 2210",
    location: "Al Khobar, Rakah",
    skuSummary: "4x Qassim Organic Rutab Dates (5kg)",
    status: "Pending Review",
    gateway: "Cash on Delivery",
    total: 410.0,
  },
  {
    id: "NX-89417",
    priority: null,
    customer: "Fahad Al-Harbi",
    phone: "+966 53 *** 7712",
    location: "Madinah, Al-Munawwarah",
    skuSummary: "1x Wireless Charging Dock (Customized)",
    status: "Delivered",
    gateway: "Apple Pay",
    total: 260.0,
  },
  {
    id: "NX-89416",
    priority: null,
    customer: "Layla Al-Harthy",
    phone: "+966 58 *** 3344",
    location: "Makkah, Al-Aziziyah",
    skuSummary: "2x Zamzam Gift Set + 1x Prayer Rug",
    status: "Cancelled",
    gateway: "Mada",
    total: 540.0,
  },
  {
    id: "NX-89415",
    priority: null,
    customer: "Yousef Al-Qahtani",
    phone: "+966 59 *** 5567",
    location: "Khobar, Corniche",
    skuSummary: "1x Falcon Leather Travel Case",
    status: "Processing",
    gateway: "Mada",
    total: 1980.0,
  },
];