export const customerSegments = ["All Segments", "Retail", "Merchant B2B"];
export const customerStatuses = ["All Statuses", "Active", "Suspended"];

export const mockCustomers = [
  {
    id: "cus-1",
    name: "Sultan Al-Otaibi",
    email: "s.otaibi@email.sa",
    phone: "+966 50 *** 4821",
    segment: "Retail",
    location: "Riyadh",
    orders: 34,
    totalSpent: 48250,
    status: "Active",
  },
  {
    id: "cus-2",
    name: "Noura Al-Ghamdi",
    email: "n.ghamdi@rawafed.sa",
    phone: "+966 54 *** 8912",
    segment: "Merchant B2B",
    location: "Jeddah",
    orders: 118,
    totalSpent: 184900,
    status: "Active",
  },
  {
    id: "cus-3",
    name: "Abdulrahman Al-Dosari",
    email: "a.dosari@tamkeen.sa",
    phone: "+966 55 *** 3109",
    segment: "Merchant B2B",
    location: "Dammam",
    orders: 62,
    totalSpent: 92400,
    status: "Active",
  },
  {
    id: "cus-4",
    name: "Reem Al-Khatib",
    email: "reem.k@domain.com",
    phone: "+966 56 *** 7421",
    segment: "Retail",
    location: "Al Khobar",
    orders: 12,
    totalSpent: 6420,
    status: "Active",
  },
  {
    id: "cus-5",
    name: "Fahad Al-Harbi",
    email: "fahad.harbi@outlook.sa",
    phone: "+966 53 *** 1198",
    segment: "Retail",
    location: "Madinah",
    orders: 5,
    totalSpent: 1890,
    status: "Suspended",
  },
  {
    id: "cus-6",
    name: "Sarah Al-Shehri",
    email: "procurement@shehri-est.com",
    phone: "+966 57 *** 6652",
    segment: "Merchant B2B",
    location: "Abha",
    orders: 47,
    totalSpent: 74150,
    status: "Active",
  },
  {
    id: "cus-7",
    name: "Mohammed Al-Zahrani",
    email: "m.zahrani@gmail.com",
    phone: "+966 50 *** 9033",
    segment: "Retail",
    location: "Tabuk",
    orders: 21,
    totalSpent: 14800,
    status: "Active",
  },
  {
    id: "cus-8",
    name: "Laila Al-Mutairi",
    email: "laila.mutairi@cloud.sa",
    phone: "+966 59 *** 2314",
    segment: "Retail",
    location: "Riyadh",
    orders: 8,
    totalSpent: 3740,
    status: "Active",
  },
];

export const mockCustomersTotalCount = 42850;